import { Box, Heading } from '@chakra-ui/react'
import Head from 'next/head'
import connecMongo from '../db/db';
import {MemberModel} from '../db/models/MemberModel';
import {Url} from 'url';


import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Tooltip
} from '@chakra-ui/react'

export default function Home({members}) {
  console.log(members)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading>
        Database Dashboard 
      </Heading>
      <Box as="main">
        {/* Table of members */}

        <TableContainer my="3">
          <Table variant="striped">
              <Thead>
                <Tr>
                  <Th>Name(s)</Th>
                  <Th>Surname</Th>
                  <Th>Email</Th>
                  <Th>Contact</Th>
                  <Th>Employment Status</Th>
                  <Th>Actively Seeking Work</Th>
                </Tr>
              </Thead>
              <Tbody>
                {/* Render Each Record */}

                {
                  members.map(member => (
                    <Tooltip label={`View ${member.firstNames}'s full profile`} key={member._id} >
                      <Tr 
                      cursor="pointer"
                      _hover={
                        {backgroundColor: "blue.100",}
                      }
                    >
                        <Td>{member.firstNames}</Td>
                        <Td>{member.lastName}</Td>
                        <Td>{member.email}</Td>
                        <Td>{member.contact}</Td>
                        <Td>{member.employmentStatus}</Td>
                        <Td>{member.isSeekingWork ? "Yes" : "No" }</Td>
                        <Td></Td>
                    </Tr>
                    </Tooltip>
                  ))
                }
              </Tbody>
          </Table>
        </TableContainer>

      </Box>     
    </div>
  )
}

export async function getServerSideProps(){
  try{
    await connecMongo();

  
        //create document
        const members = await MemberModel.find();
        
        const jsonData = JSON.stringify(members);


        return {
          props: {members: JSON.parse(jsonData)}
        }
  


}catch(error){
    console.log(error)
    return {
      props: {
        members: []
      }
    }
}
}